version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./app:/var/www/html/app
            - ./public:/var/www/html/public
            - ./documentation:/var/www/html/documentation
            - ./tests:/var/www/html/tests
            - ./writable:/var/www/html/writable
        environment:
            - CI_ENVIRONMENT=development
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - ci-books-network

    # db mysql
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: books_management_ci4
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - ci-books-network

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        restart: always
        ports:
            - "8081:80"
        depends_on:
            - mysql
        networks:
            - ci-books-network

volumes:
    mysql_data:

networks:
    ci-books-network:
        driver: bridge